### ISSUE TITLE
Grader Names Bug

### ISSUE THREAD

**Issue by rtreharne** [rtreharne/canvasadmin#20]
In Submissions table the Sync_Grades function will pull through the name of grader. It currently does this by looking at the grader_id field on the submission. If there is no grader_id set then it will scrape the name of the person who made the LAST comment.

What needs to happen is:

1. Attempt to get grader name from FIRST COMMENT.
2. Make sure comment is not made by student. If so, try next comment.
3. If no comments, or comments are made by admin use grader_id field on submission.
4. If grader_id is admin then return None.

**Comment by rtreharne** [comment]
Jack is working on this

**Comment by JackJFoster** [comment]
Changed the marker from the person who left the last comment to the person who marked the rubric. This will not work for asignments where there are no rurbrics attached. Emphasising the importance of a rubric for assignment links.  

#check rubric 
        try:

            full_rubric =  canvas_submission.full_rubric_assessment
            canvas_user = canvas.get_user(full_rubric['assessor_id'])
            graded_by = canvas_user.sortable_name
        except:
            pass
