### ISSUE TITLE
ELP Server 500.

### ISSUE THREAD

**Issue by rtreharne** [rtreharne/canvasadmin#26]
Hi team,

 

Can we look into why the following student cannot apply for an ELP please? It’s giving Server 500 error after they click on the module.

 

*<STUDENT NAME REDACTED>*

 

BIOM604

 

The assignment they want to ELP for is Short Review 2. (deadline was June 10th)

 

I’ve never seen Server 500 error from student facing view before. It comes up when trying to apply for any modules for this student.

 

Any help for a fix would be greatly appreciated!

 

 

With thanks,

 

Rob

**Comment by JackJFoster** [comment]
Issue resolved, this was due to the date in the Extensions and Exemptions expiring. 

http://canvaslens.liv.ac.uk/admin/extensions/date/7/change/ link to date change here
