### ISSUE TITLE
Batch create Calendar entries

### ISSUE THREAD

**Issue by walnuaimy** [rtreharne/canvasadmin#6]
As discussed, it would be very helpful if there were a way to batch create Canvas Calendar events corresponding to deadlines. This could be uploaded at the beginning of the semester via CSV.

Students would then see their deadlines through their Canvas app via the Calendar.

Downside would be there would be duplicates of these calendar entries once the actual assignments/quizzes are set up within each course!

**Comment by rtreharne** [comment]
Hi Waleed,

I've checked and you CAN add calendar events via the API. Will build an integration for Canvas Lens.

Will keep you updated here.

**Comment by walnuaimy** [comment]
[heart]         Al-Nuaimy, Waleed reacted to your message:
________________________________
